Adding WooCommerce Stats command
Automattic/team51-cli pull request #175
Opened 2022-12-06 22:27 UTC by cagrimmett

1. Fetches a8cteam51 sites
2. Filters out non-production sites
3. Checks for WooCommerce
4. If WooCommerce is active, check the API for stats for the given time period
5. Sort, format, and output

2022-12-09 02:25 UTC, cagrimmett commented
Changed to check Jetpack profiles by default, with the option to check production sites if needed. Cuts runtime down from 6 minutes to under 2 minutes.

2022-12-15 14:32 UTC, pippercameron requested changes

2022-12-15 14:32 UTC, spencermorin commented on src/commands/get-woocommerce-stats.php
> +				"This command will output the top grossing WooCommerce sites we support with dollar amounts and an over amount summed across all of our sites.\n
Minor, but the indentation/spacing/newlines here make the help output not line up visually with the rest of the CLI output for this and other commands. Is that intended or just a consequence of the formatting in the file?

2022-12-15 14:32 UTC, spencermorin commented on src/commands/get-woocommerce-stats.php
> +		if ( empty( $sites ) ) {
We can harden this error detection a bit more by checking `empty( $sites->blogs->blogs )`.

2022-12-15 14:32 UTC, pippercameron commented on src/commands/get-woocommerce-stats.php
> +			if ( strpos( $site->siteurl, 'mystagingwebsite.com' ) === false && strpos( $site->siteurl, 'go-vip.co' ) === false && strpos( $site->siteurl, 'wpcomstaging.com' ) === false && strpos( $site->siteu
Looking at this again after our previous conversation, it occurs to me we can make these conditionals a little more manageable by defining an array of hosts, then using `parse_url()` and `is_array()` to simplify this and avoid calling `strpos()` for each check.

Something like this:

```
$deny_list = array(
    'mystagingwebsite.com',
    'go-vip.co',
   // etc.
);

if ( ! in_array( parse_url( $site->siteurl, PHP_URL_HOST ), $deny_list ) ) {

}
```

2022-12-15 14:32 UTC, pippercameron commented on src/commands/get-woocommerce-stats.php
> +				$site_list[] = array( $site->userblog_id, $site->siteurl );
Using an associative array is generally a good idea for readability later on in the code, like on line 108.

2022-12-15 14:32 UTC, pippercameron commented on src/commands/get-woocommerce-stats.php
> +				if ( ! is_null( $plugin_list ) ) {
Any reason for using `is_null()` instead of a broader check like `empty()`?

2022-12-15 14:32 UTC, pippercameron commented on src/commands/get-woocommerce-stats.php
> +					if ( ! is_null( $plugin_list->data ) ) {
See above `is_null()` comment. :)

2022-12-15 14:32 UTC, pippercameron commented on src/commands/get-woocommerce-stats.php
> +						$plugins_array = json_decode( json_encode( $plugin_list->data ), true );
What's the reasoning for encoding then immediately decoding? Is the intent to convert data from an object to an array or something else?

2022-12-15 14:32 UTC, pippercameron commented on src/commands/get-woocommerce-stats.php
> +			$jetpack_sites_plugins = $api_helper->call_wpcom_api( 'rest/v1.1/me/sites/plugins/', array() );
May want some error checking for the response of this API request.

2022-12-15 14:32 UTC, pippercameron commented on src/commands/get-woocommerce-stats.php
> +				return $b[2] - $a[2];
Consider building this as an associative array so the comparison being done is clear.

2022-12-15 14:32 UTC, pippercameron commented on src/commands/get-woocommerce-stats.php
> +				return $carry + $site[2];
Same as previous comment above.

2023-03-01 17:41 UTC, cagrimmett commented on src/commands/stats-woocommerce-orders.php
> +		$site_count = count( $site_list );
Output an error if site count is zero

2023-03-01 17:47 UTC, cagrimmett commented on src/commands/stats-woocommerce-orders.php
> +				'Checks production sites instead of the Jetpack Profile for the sites. Takes much longer to run.'
Add the reason why we'd want to check the production site vs Jetpack Profiles

2023-03-01 17:48 UTC, cagrimmett commented on src/commands/stats-woocommerce-orders.php
> +				'Checks production sites instead of the Jetpack Profile for the sites. Takes much longer to run.'
Useful for when you think the jetpack cache is out of date for some reason.

2023-03-01 17:53 UTC, cagrimmett commented on src/commands/stats-woocommerce-orders.php
> +						if ( $site_plugin->slug === $plugin_slug && true === $site_plugin->active ) {
Add a break

2023-06-07 16:28 UTC, pippercameron approved these changes

2023-06-07 18:17 UTC, merged